[private]
default:
    just --list

# install & setup dependencies/tools
[group('dev')]
init:
  mise install

# alias k := cluster-up
# # create dev k3d cluster
# [group('dev')]
# cluster-up:
#   k3d cluster create local-k3s --image rancher/k3s:v1.26.4-k3s1

# alias kd := cluster-down
# # delete dev k3d cluster
# [group('dev')]
# cluster-down:
#   k3d cluster delete local-k3s
