version: '3.8'
services:
  postgres:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      RUST_BACKTRACE: "1"
    volumes:
      - ./.data_postgres:/var/lib/postgresql/data
      # doesnt work. get fast down request for bg worker to start
      # - ./docker/postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Increased to allow for extension compilation
    # Custom command with optimized PostgreSQL settings and extension configuration
    command: ["postgres", "-c", "max_connections=100", "-c", "shared_preload_libraries=pg_data_retention", "-c", "wal_level=logical"]
