version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      RUST_BACKTRACE: "1"
    volumes:
      - ./.data_postgres:/var/lib/postgresql/data
      # Mount a directory for initialization scripts (optional)
      # - ./init-scripts:/docker-entrypoint-initdb.d
      # For development, you might want to mount the source code
      # - .:/pgrx_data_retention:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s # Increased to allow for extension compilation
    # Custom command with optimized PostgreSQL settings and extension configuration
    command: ["postgres", "-c", "max_connections=100", "-c", "shared_buffers=256MB", "-c", "effective_cache_size=1GB", "-c", "work_mem=16MB", "-c", "maintenance_work_mem=64MB", "-c", "random_page_cost=1.1", "-c", "temp_file_limit=10GB", "-c", "log_min_duration_statement=200ms", "-c", "idle_in_transaction_session_timeout=10s", "-c", "lock_timeout=1s", "-c", "statement_timeout=60s", "-c", "shared_preload_libraries=pgrx_data_retention", "-c", "wal_level=logical"]
