[private]
default:
    just --list

# install dependencies/tools
init:
  mise install
  cargo install --locked samply
  cargo install --locked cargo-pgrx
  brew install icu4c pkg-config
  export PKG_CONFIG_PATH=/opt/homebrew/opt/icu4c/lib/pkgconfig && cargo pgrx init

# run app
[group('app')]
run:
  cd pg_data_retention && cargo pgrx run

# build app
[group('app')]
pkg:
  cd pg_data_retention && cargo pgrx package

# test
[group('app')]
test:
  cd pg_data_retention && cargo pgrx test

# cpu profiling
alias s := samply
[group('dev')]
samply:
  dotenvx run -f .env -- samply record ./pg_data_retention/target/debug/pgrx_embed_pg_data_retention

# build postgres image with extension & run
[group('docker')]
up:
  cd docker && docker-compose up -d --build

[group('docker')]
down:
  cd docker && docker-compose down -v
