name: spark-minio-clickhouse-jupyter
networks:
  spark-analytics-network:
    driver: bridge
services:
  # spark
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "8080:8080" # spark master ui
      - "7077:7077" # spark master RPC port
      - "4040:4040" # spark application ui
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077 --webui-port 8080"
    networks:
      - spark-analytics-network
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_PORT=8881
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --webui-port 8081"
    ports:
      - "8081:8081" # worker web UI
    networks:
      - spark-analytics-network
  # interactive notebook
  spark-notebook:
    build:
      context: notebook
      dockerfile: Dockerfile
    container_name: spark-notebook
    depends_on:
      - spark-master
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8888:8888" # jupyter lab ui
      - "4041:4040" # spark ui for jupyter jobs (mapped to 4041 to avoid conflicts)
    volumes:
      - ./notebook:/app
      - ./data:/home/jovyan/data
    command: jupyter lab --NotebookApp.token='' --NotebookApp.password='' --ip='0.0.0.0' --allow-root
    networks:
      - spark-analytics-network
  # s3 - minio
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "10000:9000" # API port
      - "10001:9001" # Console port
    environment:
      MINIO_ROOT_USER: "minio"
      MINIO_ROOT_PASSWORD: "minio123"
    # volumes:
    # - .data-l1:/data
    command: server /data --console-address ":9001"
    networks:
      - spark-analytics-network
  # clickhouse
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123" # HTTP API
      - "9000:9000" # Native protocol
    volumes:
      - ./.data-clickhouse:/var/lib/clickhouse
      # - ./clickhouse-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      CLICKHOUSE_USER: "default_user"
      CLICKHOUSE_PASSWORD: "default_password"
      CLICKHOUSE_DB: "default"
    networks:
      - spark-analytics-network
  clickhouse-console:
    image: ghcr.io/caioricciuti/ch-ui:latest
    container_name: clickhouse-console
    restart: always
    ports:
      - "5521:5521" # Web UI port
    environment:
      VITE_CLICKHOUSE_URL: "http://clickhouse:8123"
      VITE_CLICKHOUSE_USER: "default_user"
      VITE_CLICKHOUSE_PASS: "default_password"
    depends_on:
      - clickhouse
    networks:
      - spark-analytics-network
  # MinIO client to load initial data
  minio-client:
    image: minio/mc:latest
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " sleep 10; /usr/bin/mc alias set myminio http://minio:9000 minio minio123; /usr/bin/mc mb --ignore-existing myminio/hl-mainnet-node-data; /usr/bin/mc cp --recursive /hl-mainnet-node-data/ myminio/hl-mainnet-node-data/; exit 0; "

    volumes:
      - ./.data-l1/hl-mainnet-node-data:/hl-mainnet-node-data
    networks:
      - spark-analytics-network
