repositories:
  - name: istio
    url: https://istio-release.storage.googleapis.com/charts

releases:
  - name: istio-base
    namespace: istio-system
    createNamespace: true
    chart: istio/base
    version: ~1.25.4
  - name: istiod
    namespace: istio-system
    createNamespace: true
    chart: istio/istiod
    version: ~1.25.4
    wait: true
    timeout: 120
