[project]
name = "llm-serving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12"
dependencies = [
    "huggingface-hub[cli]>=0.20.0",
    "click>=8.0.0",
    "lm-eval[api]>=0.4.9.1",
    "modelaudit>=0.2.1",
]
