[private]
default:
    just --list

# install dependencies/tools
init:
  mise install
  pre-commit install
  cd load-tests && go install go.k6.io/xk6/cmd/xk6@latest
  cd load-tests && xk6 build --with github.com/grafana/xk6-sql --with github.com/grafana/xk6-sql-driver-postgres

[group('docker')]
up: down
  docker compose up -d

[group('docker')]
down:
  docker compose down -v

# [group('load-test')]
# load:
#   cd load-tests && ./k6 run insert-data.js
