[private]
default:
    just --list

# install & setup dependencies/tools
[group('dev')]
init:
  mise install

alias k := cluster-up
# create dev k3d cluster
[group('dev')]
cluster-up:
  k3d cluster create local-k8s --image rancher/k3s:v1.33.1-k3s1

alias kd := cluster-down
# delete dev k3d cluster
[group('dev')]
cluster-down:
  k3d cluster delete local-k8s

alias run := operator-run
# run operator
[group('operator')]
operator-run:
  cd operator && cargo run

alias build := contracts-build
# run contracts
[group('contracts')]
contracts-build:
  cd contracts && forge build
