[private]
default:
    just --list

# install dependencies/tools
init:
  mise install
  cargo install --locked samply
  cargo install --locked cargo-pgrx

[group('app')]
run:
  dotenvx run -f .env -- cargo run

alias s := samply
[group('dev')]
samply:
  dotenvx run -f .env -- samply record ./target/debug/pgrx-replication-kafka
