[private]
default:
    just --list

init:
  mise install
  pre-commit install
  cd load-tests && go install go.k6.io/xk6/cmd/xk6@latest
  cd load-tests && xk6 build --with github.com/grafana/xk6-sql --with github.com/grafana/xk6-sql-driver-postgres

[group('app')]
run:
  ./mvnw spring-boot:run

[group('app')]
test:
  ./mvnw test

[group('fmt')]
fmt:
  ./mvnw com.spotify.fmt:fmt-maven-plugin:format

[group('docker')]
up: down
  cd docker && docker compose up -d

[group('docker')]
down:
  cd docker && docker compose down -v

[group('load-test')]
load:
  cd load-tests && ./k6 run insert-data.js
